title : Wall-E - Jekyll
description: 'A Modern Jekyll Theme'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: https://marvinminblog.github.io
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
